name: Release

on:
  release:
    types: [published]
  push:
    tags:
      - 'v*'
  workflow_dispatch:

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20.x'
        cache: 'npm'

    - name: Install dependencies
      run: npm install

    - name: Verify version
      run: |
        VERSION=$(node -p "require('./package.json').version")
        if [ "$VERSION" != "0.0.1" ]; then
          echo "Version mismatch! Expected 0.0.1, got $VERSION"
          exit 1
        fi
        echo "Version verified: $VERSION"

    - name: Build project
      run: npm run build

    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: build-artifacts
        path: build/
        retention-days: 30